### PR TITLE
Enhance force-chatter node

### PR DESCRIPTION
**Pull request by vqh-quanghuy**
Dear moriuchi, 
I have confirmed my new "load more group" button in "force-chatter" also added some enhance for the node too. In my case, to check 2 button I have a mention list with 400 persons, 2 groups and each time it load will add more 50 persons. So if the user have lower than 50 the button will be disabled. Can you take a look by, thank you!

### CODE REVIEW

**Comment by moriuchi** [comment]
Dear OrisVN,
I checked with 444 users, 177 groups of organizations.
Did you hide the "load more group" button in the case of "Get Group Feed"?
Also, in the case of "Post Feed", why did you add one group each with the "load more group" button?

I think the following is a glitch, can you please confirm it?
1. When I clicked "load more user" button → deploy → restarted node-red, only the first 50 users were retrieved.
2. Click "load more group" button → Done the node edit → Open the node edit, the first group is displayed as a duplicate (the number of "load more group" is also one more)
3. When I click "load more group" button → deploy → restart the node-red, only the first one group were retrieved.

**Comment by vqh-quanghuy** [comment]
Dear moriuchi, 
I have confirmed some of the glitch and fix it. With the "Load more groups" button at tab "Get Group Feed" issue, after reconsider it, I think it's not really necessary to put the button there when it load same groups list data as "Post feed".
In case of "load more group" only add 1 group each click, I have fix that and set it load 50 groups/ time.
With the glitch after clicked "Load more user/ group" button -> deploy -> restart node-red and only first 50 users and first group load out. Actually this depend on the source code and limit API call data per time of Salesforce. According to the Salesforce docs, I find it limit is 100 data per call, you can see it here [https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/resources_knowledge_support_artlist.htm?search_text=pageSize](url) so to get the stability in the performance, I set it 50.
The "load more group" load out a duplicate glitch, I have check it and fix the issue. will make a new Pull Request for you soon. Thanks !

**Comment by moriuchi** [comment]
>With the "Load more groups" button at tab "Get Group Feed" issue, after reconsider it, I think it's not really necessary to put the button there when it load same groups list data as "Post feed".

>With the glitch after clicked "Load more user/ group" button -> deploy -> restart node-red and only first 50 users and first group load out. Actually this depend on the source code and limit API call data per time of Salesforce. According to the Salesforce docs, I find it limit is 100 data per call,

==> I understand.

>In case of "load more group" only add 1 group each click, I have fix that and set it load 50 groups/ time.

>The "load more group" load out a duplicate glitch, I have check it and fix the issue. will make a new Pull Request for you soon.

==> We have confirmed that there is no problem.

**Comment by vqh-quanghuy** [comment]
Hi moriuchi,
As I see you have merged my pull request in, thank you! But seem like you haven't update the source in [https://flows.nodered.org/node/node-red-contrib-force](url) yet. Can you confirm it ?

**Comment by moriuchi** [comment]
Dear OrisVN,
After publishing the updated node to npm, it didn't seem to be reflected in the Flow Library.
I added this to the Flow Library and confirmed that the updated version can be installed on node-red.

**Comment by vqh-quanghuy** [comment]
> 
> 
> Dear OrisVN,
> After publishing the updated node to npm, it didn't seem to be reflected in the Flow Library.
> I added this to the Flow Library and confirmed that the updated version can be installed on node-red.

Thank you, I have confirmed that. The flow version work well now !

**Pull request merged**
